// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/microhq/stream-srv/proto/stream/stream.proto

package go_micro_srv_stream

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_16e525298da53f3d, []int{0}
}

func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (m *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(m, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type CreateResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateResponse) Reset()         { *m = CreateResponse{} }
func (m *CreateResponse) String() string { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()    {}
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_16e525298da53f3d, []int{1}
}

func (m *CreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResponse.Unmarshal(m, b)
}
func (m *CreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResponse.Marshal(b, m, deterministic)
}
func (m *CreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResponse.Merge(m, src)
}
func (m *CreateResponse) XXX_Size() int {
	return xxx_messageInfo_CreateResponse.Size(m)
}
func (m *CreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResponse proto.InternalMessageInfo

type Msg struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Msg) Reset()         { *m = Msg{} }
func (m *Msg) String() string { return proto.CompactTextString(m) }
func (*Msg) ProtoMessage()    {}
func (*Msg) Descriptor() ([]byte, []int) {
	return fileDescriptor_16e525298da53f3d, []int{2}
}

func (m *Msg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Msg.Unmarshal(m, b)
}
func (m *Msg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Msg.Marshal(b, m, deterministic)
}
func (m *Msg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Msg.Merge(m, src)
}
func (m *Msg) XXX_Size() int {
	return xxx_messageInfo_Msg.Size(m)
}
func (m *Msg) XXX_DiscardUnknown() {
	xxx_messageInfo_Msg.DiscardUnknown(m)
}

var xxx_messageInfo_Msg proto.InternalMessageInfo

func (m *Msg) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Msg) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type PubResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PubResponse) Reset()         { *m = PubResponse{} }
func (m *PubResponse) String() string { return proto.CompactTextString(m) }
func (*PubResponse) ProtoMessage()    {}
func (*PubResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_16e525298da53f3d, []int{3}
}

func (m *PubResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PubResponse.Unmarshal(m, b)
}
func (m *PubResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PubResponse.Marshal(b, m, deterministic)
}
func (m *PubResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PubResponse.Merge(m, src)
}
func (m *PubResponse) XXX_Size() int {
	return xxx_messageInfo_PubResponse.Size(m)
}
func (m *PubResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PubResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PubResponse proto.InternalMessageInfo

type SubscribeRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubscribeRequest) Reset()         { *m = SubscribeRequest{} }
func (m *SubscribeRequest) String() string { return proto.CompactTextString(m) }
func (*SubscribeRequest) ProtoMessage()    {}
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_16e525298da53f3d, []int{4}
}

func (m *SubscribeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscribeRequest.Unmarshal(m, b)
}
func (m *SubscribeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscribeRequest.Marshal(b, m, deterministic)
}
func (m *SubscribeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscribeRequest.Merge(m, src)
}
func (m *SubscribeRequest) XXX_Size() int {
	return xxx_messageInfo_SubscribeRequest.Size(m)
}
func (m *SubscribeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscribeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SubscribeRequest proto.InternalMessageInfo

func (m *SubscribeRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateRequest)(nil), "go.micro.srv.stream.CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "go.micro.srv.stream.CreateResponse")
	proto.RegisterType((*Msg)(nil), "go.micro.srv.stream.Msg")
	proto.RegisterType((*PubResponse)(nil), "go.micro.srv.stream.PubResponse")
	proto.RegisterType((*SubscribeRequest)(nil), "go.micro.srv.stream.SubscribeRequest")
}

func init() {
	proto.RegisterFile("github.com/microhq/stream-srv/proto/stream/stream.proto", fileDescriptor_16e525298da53f3d)
}

var fileDescriptor_16e525298da53f3d = []byte{
	// 255 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0x41, 0x4b, 0xfb, 0x40,
	0x10, 0xc5, 0xb3, 0xf9, 0xff, 0x89, 0x74, 0xb4, 0xa5, 0x8c, 0x97, 0x90, 0x8b, 0x61, 0x45, 0x88,
	0x07, 0x37, 0xa2, 0x07, 0x3f, 0x80, 0x27, 0x0f, 0x85, 0x90, 0x7c, 0x82, 0x6c, 0xb2, 0x24, 0x0b,
	0xc6, 0x6d, 0x77, 0x36, 0xfd, 0xf0, 0x9e, 0x84, 0x6d, 0x2c, 0x5a, 0x52, 0x4f, 0xbb, 0xcc, 0xbc,
	0xc7, 0xfb, 0x3d, 0x06, 0x5e, 0x3a, 0xed, 0xfa, 0x51, 0x8a, 0xc6, 0x0c, 0xf9, 0xa0, 0x1b, 0x6b,
	0xfa, 0x5d, 0x4e, 0xce, 0xaa, 0x7a, 0x78, 0x20, 0xbb, 0xcf, 0xb7, 0xd6, 0x38, 0x33, 0x0d, 0xa6,
	0x47, 0xf8, 0x19, 0x5e, 0x77, 0x46, 0x78, 0x83, 0x20, 0xbb, 0x17, 0x87, 0x15, 0xbf, 0x81, 0xe5,
	0xab, 0x55, 0xb5, 0x53, 0xa5, 0xda, 0x8d, 0x8a, 0x1c, 0xae, 0x20, 0xd4, 0x6d, 0xcc, 0x52, 0x96,
	0x2d, 0xca, 0x50, 0xb7, 0x7c, 0x0d, 0xab, 0x6f, 0x01, 0x6d, 0xcd, 0x07, 0x29, 0x7e, 0x0f, 0xff,
	0x36, 0xd4, 0x9d, 0x0a, 0x11, 0xe1, 0x7f, 0x5b, 0xbb, 0x3a, 0x0e, 0x53, 0x96, 0x5d, 0x95, 0xfe,
	0xcf, 0x97, 0x70, 0x59, 0x8c, 0xf2, 0xe8, 0xe4, 0xb0, 0xae, 0x46, 0x49, 0x8d, 0xd5, 0xf2, 0x5c,
	0xde, 0xd3, 0x27, 0x83, 0xa8, 0xf2, 0x6c, 0x58, 0x41, 0x74, 0x88, 0x46, 0x2e, 0x66, 0xd8, 0xc5,
	0x2f, 0xf0, 0xe4, 0xf6, 0x4f, 0xcd, 0x44, 0x10, 0xe0, 0x1b, 0x5c, 0x14, 0xa3, 0x7c, 0xd7, 0xd4,
	0x63, 0x3c, 0xeb, 0xd8, 0x50, 0x97, 0xa4, 0xb3, 0x9b, 0x9f, 0x55, 0x82, 0x8c, 0x61, 0x01, 0x8b,
	0x63, 0x1d, 0xbc, 0x9b, 0xb5, 0x9c, 0xd6, 0x4d, 0xce, 0x66, 0xf2, 0xe0, 0x91, 0xc9, 0xc8, 0x5f,
	0xea, 0xf9, 0x2b, 0x00, 0x00, 0xff, 0xff, 0x3a, 0x5c, 0xfd, 0x37, 0xe4, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StreamClient is the client API for Stream service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StreamClient interface {
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
	Publish(ctx context.Context, opts ...grpc.CallOption) (Stream_PublishClient, error)
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (Stream_SubscribeClient, error)
}

type streamClient struct {
	cc *grpc.ClientConn
}

func NewStreamClient(cc *grpc.ClientConn) StreamClient {
	return &streamClient{cc}
}

func (c *streamClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, "/go.micro.srv.stream.Stream/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *streamClient) Publish(ctx context.Context, opts ...grpc.CallOption) (Stream_PublishClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Stream_serviceDesc.Streams[0], "/go.micro.srv.stream.Stream/Publish", opts...)
	if err != nil {
		return nil, err
	}
	x := &streamPublishClient{stream}
	return x, nil
}

type Stream_PublishClient interface {
	Send(*Msg) error
	CloseAndRecv() (*PubResponse, error)
	grpc.ClientStream
}

type streamPublishClient struct {
	grpc.ClientStream
}

func (x *streamPublishClient) Send(m *Msg) error {
	return x.ClientStream.SendMsg(m)
}

func (x *streamPublishClient) CloseAndRecv() (*PubResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(PubResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *streamClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (Stream_SubscribeClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Stream_serviceDesc.Streams[1], "/go.micro.srv.stream.Stream/Subscribe", opts...)
	if err != nil {
		return nil, err
	}
	x := &streamSubscribeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Stream_SubscribeClient interface {
	Recv() (*Msg, error)
	grpc.ClientStream
}

type streamSubscribeClient struct {
	grpc.ClientStream
}

func (x *streamSubscribeClient) Recv() (*Msg, error) {
	m := new(Msg)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// StreamServer is the server API for Stream service.
type StreamServer interface {
	Create(context.Context, *CreateRequest) (*CreateResponse, error)
	Publish(Stream_PublishServer) error
	Subscribe(*SubscribeRequest, Stream_SubscribeServer) error
}

func RegisterStreamServer(s *grpc.Server, srv StreamServer) {
	s.RegisterService(&_Stream_serviceDesc, srv)
}

func _Stream_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/go.micro.srv.stream.Stream/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Stream_Publish_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StreamServer).Publish(&streamPublishServer{stream})
}

type Stream_PublishServer interface {
	SendAndClose(*PubResponse) error
	Recv() (*Msg, error)
	grpc.ServerStream
}

type streamPublishServer struct {
	grpc.ServerStream
}

func (x *streamPublishServer) SendAndClose(m *PubResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *streamPublishServer) Recv() (*Msg, error) {
	m := new(Msg)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Stream_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StreamServer).Subscribe(m, &streamSubscribeServer{stream})
}

type Stream_SubscribeServer interface {
	Send(*Msg) error
	grpc.ServerStream
}

type streamSubscribeServer struct {
	grpc.ServerStream
}

func (x *streamSubscribeServer) Send(m *Msg) error {
	return x.ServerStream.SendMsg(m)
}

var _Stream_serviceDesc = grpc.ServiceDesc{
	ServiceName: "go.micro.srv.stream.Stream",
	HandlerType: (*StreamServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Stream_Create_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Publish",
			Handler:       _Stream_Publish_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Subscribe",
			Handler:       _Stream_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "github.com/microhq/stream-srv/proto/stream/stream.proto",
}
