// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/stream/stream.proto

package go_micro_srv_stream

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b2373f7d4156930, []int{0}
}

func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (m *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(m, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type CreateResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateResponse) Reset()         { *m = CreateResponse{} }
func (m *CreateResponse) String() string { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()    {}
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b2373f7d4156930, []int{1}
}

func (m *CreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResponse.Unmarshal(m, b)
}
func (m *CreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResponse.Marshal(b, m, deterministic)
}
func (m *CreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResponse.Merge(m, src)
}
func (m *CreateResponse) XXX_Size() int {
	return xxx_messageInfo_CreateResponse.Size(m)
}
func (m *CreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResponse proto.InternalMessageInfo

type Msg struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Msg) Reset()         { *m = Msg{} }
func (m *Msg) String() string { return proto.CompactTextString(m) }
func (*Msg) ProtoMessage()    {}
func (*Msg) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b2373f7d4156930, []int{2}
}

func (m *Msg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Msg.Unmarshal(m, b)
}
func (m *Msg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Msg.Marshal(b, m, deterministic)
}
func (m *Msg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Msg.Merge(m, src)
}
func (m *Msg) XXX_Size() int {
	return xxx_messageInfo_Msg.Size(m)
}
func (m *Msg) XXX_DiscardUnknown() {
	xxx_messageInfo_Msg.DiscardUnknown(m)
}

var xxx_messageInfo_Msg proto.InternalMessageInfo

func (m *Msg) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Msg) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type PubResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PubResponse) Reset()         { *m = PubResponse{} }
func (m *PubResponse) String() string { return proto.CompactTextString(m) }
func (*PubResponse) ProtoMessage()    {}
func (*PubResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b2373f7d4156930, []int{3}
}

func (m *PubResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PubResponse.Unmarshal(m, b)
}
func (m *PubResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PubResponse.Marshal(b, m, deterministic)
}
func (m *PubResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PubResponse.Merge(m, src)
}
func (m *PubResponse) XXX_Size() int {
	return xxx_messageInfo_PubResponse.Size(m)
}
func (m *PubResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PubResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PubResponse proto.InternalMessageInfo

type SubscribeRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubscribeRequest) Reset()         { *m = SubscribeRequest{} }
func (m *SubscribeRequest) String() string { return proto.CompactTextString(m) }
func (*SubscribeRequest) ProtoMessage()    {}
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b2373f7d4156930, []int{4}
}

func (m *SubscribeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscribeRequest.Unmarshal(m, b)
}
func (m *SubscribeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscribeRequest.Marshal(b, m, deterministic)
}
func (m *SubscribeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscribeRequest.Merge(m, src)
}
func (m *SubscribeRequest) XXX_Size() int {
	return xxx_messageInfo_SubscribeRequest.Size(m)
}
func (m *SubscribeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscribeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SubscribeRequest proto.InternalMessageInfo

func (m *SubscribeRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func init() {
	proto.RegisterType((*CreateRequest)(nil), "go.micro.srv.stream.CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "go.micro.srv.stream.CreateResponse")
	proto.RegisterType((*Msg)(nil), "go.micro.srv.stream.Msg")
	proto.RegisterType((*PubResponse)(nil), "go.micro.srv.stream.PubResponse")
	proto.RegisterType((*SubscribeRequest)(nil), "go.micro.srv.stream.SubscribeRequest")
}

func init() { proto.RegisterFile("proto/stream/stream.proto", fileDescriptor_1b2373f7d4156930) }

var fileDescriptor_1b2373f7d4156930 = []byte{
	// 235 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0x41, 0x4b, 0xc3, 0x30,
	0x1c, 0xc5, 0x9b, 0x4e, 0x2a, 0xfe, 0x75, 0x63, 0xfc, 0xbd, 0xd4, 0x5e, 0x2c, 0x11, 0xa1, 0x5e,
	0xa2, 0xe8, 0x47, 0xf0, 0xe4, 0x61, 0x50, 0xda, 0x4f, 0x90, 0xac, 0xa1, 0x06, 0x9c, 0x99, 0xf9,
	0x27, 0x7e, 0x78, 0x4f, 0x42, 0x36, 0x87, 0x8e, 0xd4, 0x53, 0x42, 0xde, 0x7b, 0xbc, 0xdf, 0x23,
	0x70, 0xb5, 0x75, 0xd6, 0xdb, 0x7b, 0xf2, 0x4e, 0xcb, 0xcd, 0xfe, 0x10, 0xf1, 0x0d, 0x2f, 0x47,
	0x2b, 0x36, 0x66, 0xed, 0xac, 0x20, 0xf7, 0x29, 0x76, 0x12, 0xbf, 0x86, 0xf9, 0xb3, 0xd3, 0xd2,
	0xeb, 0x4e, 0x7f, 0x04, 0x4d, 0x1e, 0x17, 0x90, 0x9b, 0xa1, 0x64, 0x35, 0x6b, 0x66, 0x5d, 0x6e,
	0x06, 0xbe, 0x84, 0xc5, 0x8f, 0x81, 0xb6, 0xf6, 0x9d, 0x34, 0xbf, 0x83, 0xd9, 0x8a, 0xc6, 0x63,
	0x23, 0x22, 0x9c, 0x0c, 0xd2, 0xcb, 0x32, 0xaf, 0x59, 0x73, 0xd1, 0xc5, 0x3b, 0x9f, 0xc3, 0x79,
	0x1b, 0xd4, 0x21, 0xc9, 0x61, 0xd9, 0x07, 0x45, 0x6b, 0x67, 0xd4, 0x54, 0xdf, 0xe3, 0x17, 0x83,
	0xa2, 0x8f, 0x6c, 0xd8, 0x43, 0xb1, 0xab, 0x46, 0x2e, 0x12, 0xec, 0xe2, 0x0f, 0x78, 0x75, 0xf3,
	0xaf, 0x67, 0x4f, 0x90, 0xe1, 0x0b, 0x9c, 0xb6, 0x41, 0xbd, 0x19, 0x7a, 0xc5, 0x32, 0x99, 0x58,
	0xd1, 0x58, 0xd5, 0x49, 0xe5, 0xf7, 0x94, 0xac, 0x61, 0xd8, 0xc2, 0xd9, 0x61, 0x0e, 0xde, 0x26,
	0x23, 0xc7, 0x73, 0xab, 0xc9, 0x4e, 0x9e, 0x3d, 0x30, 0x55, 0xc4, 0x9f, 0x7a, 0xfa, 0x0e, 0x00,
	0x00, 0xff, 0xff, 0x2f, 0x1c, 0xd3, 0xfd, 0xc6, 0x01, 0x00, 0x00,
}
